light:
  - angle-left
  - angle-right
  - arrow-down
  - arrow-up
  - bars
  - calendar-check
  - eye
  - face-smile-beam
  - face-grin
  - location-dot
  - pencil
  - share-nodes
  - sitemap
  - trash
  - user-magnifying-glass
  - user-ninja
  - user-tie
